<a href="https://colab.research.google.com/github/Sameer-Ahmed7/Deep_learning_Practice/blob/IRIS/Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#!pip install tensorflow --upgrade

In [0]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [0]:
df = pd.read_csv("IRIS.csv")

In [207]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [208]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [209]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal_length    150 non-null float64
sepal_width     150 non-null float64
petal_length    150 non-null float64
petal_width     150 non-null float64
species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [0]:
from sklearn.utils import shuffle
shuffleData = shuffle(df)

In [211]:
shuffleData.head(10)

sepal_length  sepal_width  petal_length  petal_width          species
135           7.7          3.0           6.1          2.3   Iris-virginica
149           5.9          3.0           5.1          1.8   Iris-virginica
10            5.4          3.7           1.5          0.2      Iris-setosa
7             5.0          3.4           1.5          0.2      Iris-setosa
77            6.7          3.0           5.0          1.7  Iris-versicolor
67            5.8          2.7           4.1          1.0  Iris-versicolor
49            5.0          3.3           1.4          0.2      Iris-setosa
69            5.6          2.5           3.9          1.1  Iris-versicolor
142           5.8          2.7           5.1          1.9   Iris-virginica
119           6.0          2.2           5.0          1.5   Iris-virginica

In [212]:
shuffleData.species.unique()

array(['Iris-virginica', 'Iris-setosa', 'Iris-versicolor'], dtype=object)

In [0]:
shuffleData[shuffleData.species == "Iris-setosa"]=0

In [214]:
shuffleData.species.unique()

array(['Iris-virginica', 0, 'Iris-versicolor'], dtype=object)

In [0]:
shuffleData[shuffleData.species == "Iris-versicolor"]=1

In [0]:
shuffleData[shuffleData.species == "Iris-virginica"]=2

In [217]:
shuffleData.species.unique()

array([2, 0, 1])

In [218]:
shuffleData.shape

(150, 5)

In [0]:
train_x = shuffleData.iloc[:120,:4]

In [220]:
train_x.head()

sepal_length  sepal_width  petal_length  petal_width
135           2.0          2.0           2.0          2.0
149           2.0          2.0           2.0          2.0
10            0.0          0.0           0.0          0.0
7             0.0          0.0           0.0          0.0
77            1.0          1.0           1.0          1.0

In [0]:
train_y = shuffleData.iloc[:120,4]

In [222]:
train_y

135    2
149    2
10     0
7      0
77     1
      ..
120    2
38     0
134    2
40     0
107    2
Name: species, Length: 120, dtype: int64

In [0]:
test_x = shuffleData.iloc[120:,:4]

In [0]:
test_y = shuffleData.iloc[120:,4]

In [225]:
train_x.shape,train_y.shape,test_x.shape,test_y.shape

((120, 4), (120,), (30, 4), (30,))

In [0]:
train_x = train_x.values

In [0]:

test_x = test_x.values

In [0]:
from tensorflow.keras import models,layers

In [0]:
def buildModel():
  model = models.Sequential()
  model.add(layers.Dense(50,activation="relu"))
  model.add(layers.Dense(3,activation="softmax"))
  model.compile(optimizer="rmsprop",loss="categorical_crossentropy",metrics=['accuracy'])
  return model

In [0]:
model = buildModel()

In [0]:
train_y = train_y.values
test_y = test_y.values

In [0]:
from tensorflow.keras.utils import to_categorical

In [0]:
train_labels = to_categorical(train_y)
test_labels = to_categorical(test_y)

In [234]:
model.fit(train_x,train_labels,epochs=60)

Train on 120 samples
Epoch 1/60
120/120 [==============================] - 0s 3ms/sample - loss: 1.1762 - accuracy: 0.4000
Epoch 2/60
120/120 [==============================] - 0s 99us/sample - loss: 1.0756 - accuracy: 0.2667
Epoch 3/60
120/120 [==============================] - 0s 122us/sample - loss: 1.0221 - accuracy: 0.3500
Epoch 4/60
120/120 [==============================] - 0s 89us/sample - loss: 0.9848 - accuracy: 0.3500
Epoch 5/60
120/120 [==============================] - 0s 105us/sample - loss: 0.9573 - accuracy: 0.4583
Epoch 6/60
120/120 [==============================] - 0s 121us/sample - loss: 0.9342 - accuracy: 0.6750
Epoch 7/60
120/120 [==============================] - 0s 104us/sample - loss: 0.9155 - accuracy: 0.6750
Epoch 8/60
120/120 [==============================] - 0s 140us/sample - loss: 0.9000 - accuracy: 0.6750
Epoch 9/60
120/120 [==============================] - 0s 113us/sample - loss: 0.8870 - accuracy: 0.6750
Epoch 10/60
120/120 [==========================

In [235]:
test_loss, test_acc = model.evaluate(test_x,test_labels)

30/30 [==============================] - 0s 3ms/sample - loss: 0.6355 - accuracy: 1.0000


In [237]:
df.species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [0]:
predict = model.predict(test_x)

In [0]:
def prediction(value):
  if value.argmax()==0:
    pred = 'Iris-setosa'
  elif value.argmax() ==1:
    pred = "Iris-versicolor"
  else:
    pred = "Iris-virginica" 
  return pred   

In [0]:
predicted = []
for i in range(len(predict)):
  a = prediction(predict[i])
  predicted.append(a)

In [243]:
predicted,test_y

(['Iris-virginica',
  'Iris-setosa',
  'Iris-versicolor',
  'Iris-setosa',
  'Iris-setosa',
  'Iris-setosa',
  'Iris-versicolor',
  'Iris-versicolor',
  'Iris-setosa',
  'Iris-virginica',
  'Iris-setosa',
  'Iris-versicolor',
  'Iris-virginica',
  'Iris-virginica',
  'Iris-setosa',
  'Iris-versicolor',
  'Iris-virginica',
  'Iris-virginica',
  'Iris-setosa',
  'Iris-versicolor',
  'Iris-virginica',
  'Iris-versicolor',
  'Iris-setosa',
  'Iris-versicolor',
  'Iris-versicolor',
  'Iris-versicolor',
  'Iris-virginica',
  'Iris-setosa',
  'Iris-setosa',
  'Iris-versicolor'],
 array([2, 0, 1, 0, 0, 0, 1, 1, 0, 2, 0, 1, 2, 2, 0, 1, 2, 2, 0, 1, 2, 1,
        0, 1, 1, 1, 2, 0, 0, 1]))

In [273]:
test_x

array([[2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [0]:
import csv
with open("test_Data.csv","w+") as f:
  write = csv.writer(f)
  write.writerow(["Species"])
  for i in range(len(predicted)):
    write.writerow([predicted[i]])

In [0]:
df1 = pd.read_csv("test_Data.csv")

In [0]:
import csv
with open("test_Data_Inputs.csv","w+") as f:
  write = csv.writer(f)
  write.writerow(['sepal_length','sepal_width',"petal_length","petal_width"])
  for i in range(len(test_x)):
    write.writerows([test_x[i]])

In [0]:
df2 = pd.read_csv("test_Data_Inputs.csv")

In [292]:
df2.head()

sepal_length  sepal_width  petal_length  petal_width
0           2.0          2.0           2.0          2.0
1           0.0          0.0           0.0          0.0
2           1.0          1.0           1.0          1.0
3           0.0          0.0           0.0          0.0
4           0.0          0.0           0.0          0.0

In [0]:
a = np.array([2.0,1.0,1.0,0.0])
a = a.reshape(1,4)

In [0]:
predicted1 = model.predict(a)

In [297]:
test_x.shape,a.shape

((30, 4), (4,))

In [300]:
b = prediction(predicted1)
print(b)

Iris-virginica
